Repository IT-Cotato/11th-TroubleLog-FE, pull requests merged in 2025-08, with the labels that each got.

#54 FEAT: 프로젝트 생성 api 연동 세팅
  src/api/project.api.ts
  src/mocks/mockProject.ts
  src/pages/Home/HomePage.tsx
  src/types/project.model.ts
Labels: ✨ Feature

#56 FEAT: 프로젝트 목록, 상세 조회, 수정, 삭제 api 연동 세팅
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/project.api.ts
  src/components/Button/CancelButton.tsx
  src/components/Button/SaveButton.tsx
  src/components/Modal/ConfirmDeleteModal.tsx
  src/components/Modal/FolderModal.tsx
  src/components/Project/ProjectAccordion.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/mockProject.ts
  src/pages/Home/HomePage.tsx
  src/routes/Router.tsx
  src/types/project.model.ts
  src/utils/getAPIResponseData.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#57 FEAT: 회원가입/로그인 api 연동
  package-lock.json
  package.json
  public/icons/purpleprivateicon.svg
  public/icons/tempimg1gray.svg
  public/icons/tempimg1purple.svg
  public/icons/tempimg2gray.svg
  public/icons/tempimg2purple.svg
  public/icons/tempimg3gray.svg
  public/icons/tempimg3purple.svg
  public/icons/tempimg4gray.svg
  public/icons/tempimg4purple.svg
  src/api/apiHeaders.ts
  src/api/auth.api.ts
  src/api/authInstance.ts
  src/components/Community/PostGuideMd.tsx
  src/components/Menu/UserMenuDropdown.tsx
  src/components/TemplateWrite/CategoryTag.tsx
  src/components/TemplateWrite/EditorBlock.tsx
  src/constants/paths.ts
  src/models/auth.model.ts
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Login/Input.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/SignPageOne.tsx
  src/pages/Login/SignPageTwo.tsx
  src/pages/TempWrite/PostSaveModal.tsx
  src/pages/TempWrite/PreviewPage.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/pages/TempWrite/TemplateSelectModal.tsx
  src/routes/Router.tsx
  src/utils/formHandlers.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature

#64 REFACTOR: '트러블슈팅 목록 조회 api 연동 세팅 및 라우팅 추가' 피드백 반영
  src/api/trouble.api.ts
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/hooks/useTroubleCards.ts
  src/mappers/cardMapper.ts
  src/mappers/troubleCard.mapper.ts
  src/mocks/handlers.ts
  src/mocks/mockProjectTroubles.ts
  src/mocks/mockTroubles.ts
  src/pages/Home/HomePage.tsx
  src/pages/MyPage/LikedPostsPage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/types/trouble.model.ts
  src/utils/troubleFormat.ts
  src/utils/troubleMapping.ts
Labels: 🛠️ Refactor

#70 REFACTOR: 실서버 연동 세팅 및 회원가입/로그인 관련 설정 수정
  src/api/apiHeaders.ts
  src/api/auth.api.ts
  src/api/authInstance.ts
  src/api/axios.ts
  src/main.tsx
  src/pages/Login/SignPageTwo.tsx
  src/routes/Router.tsx
Labels: 🛠️ Refactor, ⚙️ Setting

#73 FEAT: 프로젝트 관련 API 연동 마무리
  src/api/image.api.ts
  src/api/project.api.ts
  src/api/trouble.api.ts
  src/components/Menu/SummaryTypeDropdown.tsx
  src/components/Modal/FolderModal.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/hooks/useTroubleCards.ts
  src/mappers/troubleCard.mapper.ts
  src/pages/Home/HomePage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/types/common.model.ts
  src/types/project.model.ts
  src/types/trouble.model.ts
  src/utils/omitEmpty.ts
  src/utils/troubleMapping.ts
  src/utils/useImageUpload.ts
Labels: ✨ Feature

#76 FEAT: 검색 관련 API 연동
  src/api/trouble.api.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderWoSearch.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Project/SortButtonGroup.tsx
  src/hooks/useInfiniteCommunityTroubleSearch.ts
  src/hooks/useInfiniteMyTroubleSearch.ts
  src/hooks/useInfiniteUserTroubleSearch.ts
  src/hooks/useTroubleCards.ts
  src/layouts/MyPageLayout.tsx
  src/mappers/trouble.list-to-ts-card.ts
  src/mappers/trouble.server-to-list.ts
  src/pages/Home/HomePage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Search/SearchResultPage.tsx
  src/types/troubles.server.ts
  src/utils/troubleMapping.ts
Labels: ✨ Feature, 🛠️ Refactor

#83 FEAT: 커뮤니티 관련 변경사항 업데이트
  src/api/community.api.ts
  src/hooks/useCommunityCards.ts
  src/mappers/communityComment.mapper.ts
  src/mappers/communityPostDetail.mapper.ts
  src/pages/Community/CommunityPage.tsx
  src/types/community.model.ts
Labels: ✨ Feature, 🛠️ Refactor

#88 FIX: QA 오류 일부 해결
  src/pages/Project/ProjectDetailPage.tsx
  vercel.json
Labels: 👾 Bug

#91 FEAT: 알림 관련 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/api/alert.api.ts
  src/api/axios.ts
  src/components/Modal/NotificationModal.tsx
  src/hooks/useNotifications.ts
  src/mappers/alert.mapper.ts
  src/providers/AlertSSEProvider.tsx
  src/store/auth.ts
  src/types/alert.model.ts
  yarn.lock
Labels: ✨ Feature

#92 FEAT: QA 결과 일부 반영
  src/api/alert.api.ts
  src/components/Card/TroublogCard.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/layouts/MyPageLayout.tsx
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/pages/TempWrite/TemplateSelectModal.tsx
  src/providers/AlertSSEProvider.tsx
  src/types/alert.model.ts
Labels: ✨ Feature, 👾 Bug, 🛠️ Refactor

#96 FEAT: QA 결과 반영 (기능 관련)
  src/api/alert.api.ts
  src/api/post.api.ts
  src/api/trouble.api.ts
  src/components/Card/CardHeaderRight.tsx
  src/components/Card/CardPreviewArea.tsx
  src/components/Card/TroublogCard.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderWoSearch.tsx
  src/components/Menu/KebabMenuButton.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/MyPage/TroubleShootingCard.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Notification/NotificationToaster.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/hooks/useInfiniteCommunityTroubleSearch.ts
  src/hooks/useInfiniteMyTroubleSearch.ts
  src/hooks/useInfiniteUserTroubleSearch.ts
  src/hooks/useTroubleCards.ts
  src/layouts/MainLayout.tsx
  src/layouts/MyPageLayout.tsx
  src/mappers/alert.mapper.ts
  src/mappers/communityCard.mapper.ts
  src/mappers/myPostDetail.mapper.ts
  src/mappers/postMapper.ts
  src/mappers/trouble.list-to-ts-card.ts
  src/mappers/trouble.server-to-list.ts
  src/models/post.model.ts
  src/pages/Community/CommunityPage.tsx
  src/pages/Community/CommunityPostDetail.tsx
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Search/SearchResultPage.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/providers/AlertSSEProvider.tsx
  src/store/notification.ts
  src/types/alert.model.ts
  src/types/community.model.ts
  src/types/troubles.server.ts
  src/utils/owner.ts
Labels: ✨ Feature, 👾 Bug, 🛠️ Refactor

#100 FIX: 기능명세서 기반 에러 수정
  src/api/axios.ts
  src/components/Card/TroublogCard.tsx
  src/components/Community/PostComment.tsx
  src/components/Header/Header.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/MyPage/TroubleShootingCard.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Project/ProjectAccordion.tsx
  src/constants/paths.ts
  src/hooks/useInfiniteCommunityTroubleSearch.ts
  src/mappers/cardMapper.ts
  src/mappers/troubleCard.mapper.ts
  src/pages/Community/CommunityPostDetail.tsx
  src/pages/Error/AuthGuardPage.tsx
  src/pages/Error/NotFoundPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/routes/Router.tsx
  src/store/useMyPageStore.ts
  src/types/trouble.model.ts
  src/types/troubles.server.ts
  src/utils/url.ts
Labels: ✨ Feature, 👾 Bug, 🛠️ Refactor

#101 FIX: 배포 중 발생한 오류 해결
  src/components/Card/TroublogCard.tsx
  src/mappers/postMapper.ts
  src/mappers/trouble.server-to-list.ts
  src/mocks/mockProjectTroubles.ts
  src/mocks/mockTroubles.ts
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Login/KakaoLoginButton.tsx
  src/pages/Login/SignPageOauth.tsx
  src/pages/TempWrite/PostSuccessModal.tsx
  src/pages/TempWrite/TempWritePage.tsx
Labels: 👾 Bug

#104 FIX: 포스트 임시저장 및 수정 관련 오류 수정
  src/assets/icons/githubIcon.svg
  src/components/MyPage/MyPageSidebar.tsx
  src/components/MyPage/SummaryTypeBarChart.tsx
  src/hooks/useSummaryTypes.ts
  src/mappers/communityPostDetail.mapper.ts
  src/mappers/myPostDetail.mapper.ts
  src/models/user.model.ts
  src/pages/Community/CommunityPostDetail.tsx
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Login/OAuthPopupKakao.tsx
  src/pages/MyPage/StatisticsPage.tsx
  src/pages/Search/SearchResultPage.tsx
  src/pages/TempWrite/PreviewPage.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/types/community.model.ts
  src/utils/openOAuthPopup.ts
Labels: ✨ Feature, 👾 Bug, 🛠️ Refactor

#109 FEAT: 요약 합본 조회 라우팅
  src/components/Card/TroublogCard.tsx
  src/components/MyPage/TroubleShootingCard.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/mappers/cardMapper.ts
  src/mappers/trouble.list-to-ts-card.ts
  src/mappers/troubleCard.mapper.ts
  src/pages/Community/CommunityPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/MyPage/CombinedDetailPage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/pages/Search/SearchResultPage.tsx
  src/pages/TempWrite/PostSuccessModal.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/types/trouble.model.ts
  src/types/troubles.server.ts
  src/utils/combinedRoute.ts
Labels: ✨ Feature

#110 FIX: 타입 불일치 오류 수정
  src/hooks/useInfiniteCommunityTroubleSearch.ts
  src/mappers/trouble.server-to-list.ts
  src/mocks/mockProjectTroubles.ts
  src/mocks/mockTroubles.ts
Labels: 👾 Bug

#111 FEAT: 홈, 커뮤니티, 마이페이지, 검색 및 공통 컴포넌트 반응형 UI로 수정
  src/components/Button/CancelButton.tsx
  src/components/Button/FollowButton.tsx
  src/components/Button/SaveButton.tsx
  src/components/Card/CardFooterInfo.tsx
  src/components/Card/CardHeaderRight.tsx
  src/components/Card/CardPreviewArea.tsx
  src/components/Card/TroublogCard.tsx
  src/components/Community/PostComment.tsx
  src/components/Community/PostGuideMd.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderWoSearch.tsx
  src/components/Menu/KebabDropdown.tsx
  src/components/Menu/KebabMenuButton.tsx
  src/components/Menu/SummaryTypeDropdown.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/ConfirmDeleteModal.tsx
  src/components/Modal/FolderModal.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/MyPage/TroubleShootingCard.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Notification/NotificationToaster.tsx
  src/components/Project/SortButtonGroup.tsx
  src/layouts/MainLayout.tsx
  src/layouts/MyPageLayout.tsx
  src/mappers/troubleCard.mapper.ts
  src/pages/Community/CommunityPage.tsx
  src/pages/Community/CommunityPostDetail.tsx
  src/pages/Error/AuthGuardPage.tsx
  src/pages/Error/NotFoundPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/MyPage/LikedPostsPage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/pages/Search/SearchResultPage.tsx
Labels: ✨ Feature, 🛠️ Refactor

#113 FEAT: 이미지 관련 수정
  src/components/Card/CardPreviewArea.tsx
  src/components/Card/TroublogCard.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/TemplateWrite/EditorBlock.tsx
  src/mappers/cardMapper.ts
  src/mappers/communityCard.mapper.ts
  src/mappers/troubleCard.mapper.ts
  src/pages/EditProfile/EditProfile.tsx
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/TempWrite/TempWritePage.tsx
Labels: ✨ Feature

#118 FEAT: 일부 UI 수정
  src/components/Card/CardTitleSection.tsx
  src/components/Modal/NotificationModal.tsx
  src/pages/TempWrite/PostSuccessModal.tsx
  src/pages/TempWrite/TemplateSelectModal.tsx
Labels: 🛠️ Refactor

#119 FEAT: 랜딩 페이지 UI 구현
  src/assets/images/guide-checklist.png
  src/assets/images/guide-shot.png
  src/assets/images/hero-laptop.png
  src/assets/images/slide1.png
  src/assets/images/slide2.png
  src/assets/images/slide3.png
  src/assets/images/slide4.png
  src/components/Header/HeaderLogoOnly.tsx
  src/constants/paths.ts
  src/pages/Onboarding/IntroLandingPage.tsx
  src/routes/Router.tsx
Labels: ✨ Feature

#121 FIX: 수정사항 반영
  src/api/axios.ts
  src/api/post.api.ts
  src/components/Card/CardHeaderRight.tsx
  src/components/Modal/FolderModal.tsx
  src/components/MyPage/TroubleShootingList.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/components/Project/StatusFilterButton.tsx
  src/models/auth.model.ts
  src/pages/Community/CommunityPage.tsx
  src/pages/Error/AuthGuardPage.tsx
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Login/SignPageOauth.tsx
  src/pages/MyPage/CombinedDetailPage.tsx
  src/pages/Project/ProjectDetailPage.tsx
  src/pages/TempWrite/PostLoadingModal.tsx
  src/pages/TempWrite/PostSaveModal.tsx
  src/pages/TempWrite/PostSummaryDetail.tsx
  src/pages/TempWrite/TempWritePage.tsx
  src/types/trouble.model.ts
Labels: 👾 Bug

#123 FIX: 글 작성, 수정, 요약 관련 오류 수정
  src/api/axios.ts
  src/api/post.api.ts
  src/components/Card/CardTitleSection.tsx
  src/components/MyPage/FollowingBtn.tsx
  src/components/MyPage/MyFollowing.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/Project/ProjectFolderCard.tsx
  src/mappers/troubleCard.mapper.ts
  src/models/auth.model.ts
  src/pages/FreeFormWrite/FreeFormWritePage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Login/SignPageOauth.tsx
  src/pages/Login/SignPageOne.tsx
  src/pages/Login/SignPageTwo.tsx
  src/pages/MyPage/LikedPostsPage.tsx
  src/pages/Onboarding/IntroLandingPage.tsx
  src/pages/TempWrite/PostSaveModal.tsx
  src/pages/TempWrite/TempWritePage.tsx
Labels: 👾 Bug

#125 FIX: 토큰 갱신 로직 수정
  src/api/axios.ts
  src/pages/Login/SignPageOauth.tsx
Labels: 👾 Bug
